# Generated by Django 6.0.1 on 2026-01-26 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=50, unique=True)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "valor_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "tipo_desconto",
                    models.CharField(default="sem_desconto", max_length=50),
                ),
                ("tipo_frete", models.CharField(default="frete_fixo", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=10)),
                ("peso", models.FloatField(default=0)),
                ("quantidade_estoque", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="ItemPedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.IntegerField()),
                (
                    "preco_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="estoque.pedido",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="estoque.produto",
                    ),
                ),
            ],
        ),
    ]
