# Generated by Django 6.0.1 on 2026-01-30 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tipo_desconto',
            field=models.CharField(choices=[('percentual_10', 'Desconto de 10%'), ('percentual_15', 'Desconto de 15%'), ('percentual_20', 'Desconto de 20%'), ('fixo_50', 'Desconto fixo de R$ 50'), ('fixo_100', 'Desconto fixo de R$ 100'), ('progressivo', 'Desconto progressivo por quantidade'), ('sem_desconto', 'Sem desconto')], default='sem_desconto', help_text='Estratégia de desconto aplicada ao pedido', max_length=50, verbose_name='Tipo de Desconto'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tipo_frete',
            field=models.CharField(choices=[('por_peso', 'Frete por peso (R$ 5/kg)'), ('por_distancia', 'Frete por distância (R$ 2/km)'), ('fixo_30', 'Frete fixo de R$ 30'), ('fixo_50', 'Frete fixo de R$ 50'), ('gratis', 'Frete grátis')], default='fixo_50', help_text='Estratégia de frete aplicada ao pedido', max_length=50, verbose_name='Tipo de Frete'),
        ),
    ]
